[package]
name = "h3x"
description = "HTTP/3 message, frame, and stream primitives"
version = "0.6.2"
edition = "2024"
readme = "README.md"
repository = "https://github.com/genmeta/h3x"
license = "Apache-2.0"
keywords = ["async", "quic", "http3"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-trait = "0.1"
bytes = "1"
http = "1"
httlib-huffman = "0.3"
qbase = "0.6.4"
tokio = { version = "1", features = ["macros", "rt", "io-util", "sync"] }
