[package]
name = "h3x"
description = "HTTP/3 message, frame, and stream primitives"
version = "0.6.2"
edition = "2024"
readme = "README.md"
repository = "https://github.com/genmeta/h3x"
license = "Apache-2.0"
keywords = ["async", "quic", "http3"]
categories = ["network-programming", "asynchronous"]

[lib]
path = "src/h3x.rs"
test = true
doctest = false

[dependencies]
async-trait = "0.1"
bytes = "1"
dashmap = "6"
futures = "0.3"
http = "1"
http-body = "1"
http-body-util = "0.1"
async-stream = "0.3"
httlib-huffman = "0.3"
thiserror = "2"
qbase = { git = "https://github.com/genmeta/dquic.git", rev = "34a713b48535892ad9843cf2bb0db285e0d09439" }
qrecovery = { git = "https://github.com/genmeta/dquic.git", rev = "34a713b48535892ad9843cf2bb0db285e0d09439" }
tokio = { version = "1", features = ["macros", "rt", "io-util", "sync", "time"] }

[dev-dependencies]
scopeguard = "1"
axum = { version = "0.8", default-features = false }
tokio-util = { version = "0.7", features = ["io"] }
tower = { version = "0.5", features = ["util"] }
wasmtime = "47"
wasmtime-wasi = { version = "47", features = ["p2"] }
wasmtime-wasi-http = { version = "47", features = ["p2"] }
